version: '3.9'

services:
  jenkins:
    container_name: jenkins-server
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - "8082:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/main.yaml
    user: root
    depends_on:
      - config-server

volumes:
  jenkins_home:

networks:
  backend:
    external: true