version: '3.9'

services:
  jenkins:
    container_name: jenkins-server
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - "8082:8080"
      - "50000:50000"
    depends_on:
      - sonarqube
    volumes:
      - ./src/main/resources/init-jenkins.sh:/init-jenkins.sh:ro
      - jenkins_home:/var/jenkins_home
      - sonar_jenkins_token:/run/secrets
      - ./src/main/resources/jenkins-server.yaml:/var/jenkins_home/casc_configs/jenkins-server.yaml
      - /var/run/docker.sock:/var/run/docker.sock
      - ./src/main/resources/github-token.txt:/run/secrets/github-token.txt:ro
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
      CASC_JENKINS_CONFIG: /var/jenkins_home/casc_configs/jenkins-server.yaml
      GITHUB_USERNAME: maurolisena
      GITHUB_TOKEN_FILE: /run/secrets/github-token.txt
      SONARQUBE_TOKEN_FILE: /run/secrets/jenkins-token.txt
    entrypoint: ["/bin/sh", "/init-jenkins.sh"]
    user: root

  sonarqube:
    image: sonarqube:9.9-community
    container_name: sonarqube-server
    depends_on:
      - db
    ports:
      - "8889:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: mlisena
      SONAR_JDBC_PASSWORD: A8424628
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonar_jenkins_token:/opt/sonarqube/token_shared
    networks:
      - backend

  db:
    image: postgres:13
    container_name: sonar-db
    environment:
      POSTGRES_USER: mlisena
      POSTGRES_PASSWORD: A8424628
      POSTGRES_DB: sonar
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  sonar-init:
    image: curlimages/curl:latest
    container_name: sonar-init-script
    depends_on:
      - sonarqube
    networks:
      - backend
    volumes:
      - ./src/main/resources/init-sonar.sh:/init-sonar.sh:ro
      - sonar_jenkins_token:/token_shared
    entrypoint: [ "sh", "/init-sonar.sh" ]
    user: root

volumes:
  jenkins_home:
  sonarqube_data:
  sonarqube_logs:
  postgres_data:
  sonar_jenkins_token:

networks:
  backend:
    external: true