version: '3.9'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-server
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - "8082:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root

volumes:
  jenkins_home:

networks:
  backend:
    external: true