pipeline {
    agent any

    environment {
        REPO_URL = 'https://github.com/maurolisena/config-server.git'
        BRANCH = 'master'
        PROJECT_DIR = 'config-server'
    }

    stages {
            stage('Clonar código fuente') {
                steps {
                    git branch: "${BRANCH}", credentialsId: 'GitHub', url: "${REPO_URL}"
                }
            }

            stage('Levantar servicios') {
                steps {
                    dir("${PROJECT_DIR}") {
                        sh 'docker compose up -d'
                    }
                }
            }

            stage('Build keycloack-server') {
              steps {
                build job: 'keycloack-server'
              }
            }

            stage('Build kafka-server') {
              steps {
                build job: 'kafka-server'
              }
            }

            stage('Build eureka-server') {
              steps {
                build job: 'eureka-server'
              }
            }

            stage('Verificar servicios') {
                steps {
                    sh 'docker ps'
                }
            }
        }

    post {
        always {
            echo 'Pipeline finalizado'
        }
    }
}