version: "3.9"
services:
    redis-db:
        image: redis:7.2-alpine
        container_name: redis-db
        networks:
            - backend
        ports:
            - "6379:6379"
        restart: always

networks:
    backend:
        external: true