version: "3.9"
services:
    redis-db:
        image: redis:7.2-alpine
        container_name: redis-db
        networks:
            - backend
        ports:
            - "6379:6379"
        restart: always
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            interval: 10s
            timeout: 5s
            retries: 5

networks:
    backend:
        external: true