pipeline {
    agent any

    stages {

        stage('Limpiar contenedores y volúmenes') {
            steps {
                catchError(buildResult: 'SUCCESS', stageResult: 'UNSTABLE') {
                    sh '''
                        docker compose -f src/main/pipelines/database/redis/docker-compose.yml down --volumes --remove-orphans
                        docker volume rm redis_db_data || true
                    '''
                }
            }
        }

        stage('Construir y levantar database') {
            steps {
                catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                    echo "Construyendo imágenes y levantando database"
                    sh 'docker compose -f src/main/pipelines/database/redis/docker-compose.yml up -d'
                }
            }
        }

        stage('Esperar a RedisDB listo') {
            steps {
                echo "Esperando que RedisDB esté saludable..."
                sh '''
                    until docker exec redis_db redis-cli ping | grep -q PONG; do
                      echo "Esperando a que Redis esté listo..."
                      sleep 2
                    done
                '''
            }
        }

        stage('Verificar contenedores y logs de redis') {
            steps {
                echo "Listando contenedores activos"
                sh 'docker ps'

                echo "Mostrando últimos logs de redis_db para verificar scripts init"
                sh 'docker logs --tail 30 redis_db'
            }
        }
    }

    post {
        always {
            echo 'Pipeline finalizado'
        }
    }
}