pipeline {
    agent any

    environment {
            REPO_URL = 'https://github.com/maurolisena/product-service.git'
            BRANCH = 'main'
            PROJECT_DIR = 'product-service'
            SONARQUBE_ENV = 'SonarQube'
    }

    stages {

        stage('Clonar código fuente') {
            steps {
                git branch: "${BRANCH}", credentialsId: 'GitHub', url: "${REPO_URL}"
            }
        }

        stage('Limpiar contenedores y volúmenes') {
            steps {
                catchError(buildResult: 'SUCCESS', stageResult: 'UNSTABLE') {
                    sh '''
                        docker compose down --volumes --remove-orphans
                        docker volume rm mongo_database_data
                    '''
                }
            }
        }

        stage('Construir y levantar servicios') {
            steps {
                echo "Construyendo imágenes y levantando servicios en background"
                sh 'docker compose up -d --build'
            }
        }

        stage('Esperar a MongoDB listo') {
            steps {
                echo "Esperando que MongoDB esté saludable..."
                sh '''
                    until docker exec mongo_database mongosh --eval "db.runCommand('ping').ok" | grep 1; do
                        echo "Esperando MongoDB..."
                        sleep 5
                    done
                '''
            }
        }

        stage('Verificar contenedores y logs de mongo') {
            steps {
                echo "Listando contenedores activos"
                sh 'docker ps'

                echo "Mostrando últimos logs de mongo_database para verificar scripts init"
                sh 'docker logs --tail 30 mongo_database'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv("${SONARQUBE_ENV}") {
                    withCredentials([string(credentialsId: 'sonar-token', variable: 'SONAR_AUTH_TOKEN')]) {
                        sh '''
                            mvn clean compile sonar:sonar \
                              -Dsonar.projectKey=product-service \
                              -Dsonar.host.url=http://sonarqube:9000 \
                              -Dsonar.login=$SONAR_AUTH_TOKEN \
                              -Dsonar.java.binaries=target/classes
                        '''
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 2, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline finalizado'
        }
    }
}