pipeline {
    agent any

    environment {
            REPO_URL = 'https://github.com/maurolisena/keycloack-server.git'
            BRANCH = 'main'
            PROJECT_DIR = 'keycloack-server'
    }

    stages {

        stage('Clonar código fuente') {
            steps {
                git branch: "${BRANCH}", credentialsId: 'GitHub', url: "${REPO_URL}"
            }
        }

        stage('Levantar servicios') {
            steps {
                dir("${PROJECT_DIR}") {
                    sh 'docker compose up -d'
                }
            }
        }

        stage('Levantar servicios adicionales') {
          steps {
            build job: 'gateway-server'
          }
        }

        stage('Verificar servicios') {
            steps {
                sh 'docker ps'
            }
        }
    }

    post {
        always {
            echo 'Pipeline finalizado'
        }
    }
}